### PR TITLE
Fix/wasm

### PR DESCRIPTION
**Pull request by beltram**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

WASM compatibility and actually testing it to prevent future regressions

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by OtaK — APPROVED** [review]
Maybe revert the deleted github actions commit? I'm just thinking that if we ever want to get this into mainline openmls, we might not want to make such breaking changes

WDYT?

**Review by OtaK — CHANGES_REQUESTED** [review]
Oops

**Comment by beltram** [comment]
I did it on purpose with that in mind. If we ever get to merge this I think we'll cherry-pick commit by commit because at that time we'll have this commit history interleaved with "hacks" we won't want to merge.

**Comment by OtaK** [comment]
That's fair

LGTM :shipit:

**Pull request merged**
